<a href="https://colab.research.google.com/github/ascalmon/Colab-test/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [6]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [ ]:
y = torch.tensor([
    [1,2,3],
    [2,3,4],
    [0,0,0]
], dtype=torch.float)
y

In [ ]:
torch.ones(1,2, dtype=torch.int)

In [ ]:
torch.zeros(5,3, 2, dtype=torch.float)

In [21]:
z = torch.rand(3, 4, 2, dtype=torch.float)
z

tensor([[[0.7261, 0.1524],
         [0.8962, 0.6537],
         [0.7151, 0.8430],
         [0.9068, 0.3241]],

        [[0.2096, 0.9265],
         [0.3685, 0.7496],
         [0.3233, 0.4419],
         [0.3449, 0.5521]],

        [[0.7207, 0.8452],
         [0.0082, 0.3765],
         [0.5020, 0.4324],
         [0.4439, 0.6173]]])

In [19]:
print(y)
y[0]


tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


tensor([1., 2., 3.])

In [20]:
y[:, 1]

tensor([2., 3., 0.])

In [24]:
z[2, : ,0]

tensor([0.7207, 0.0082, 0.5020, 0.4439])

In [25]:
y[:,0]

tensor([1., 2., 0.])

In [28]:
print(y)
y.size()

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


torch.Size([3, 3])

In [29]:
print(y)
y.size()[0]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


3

In [33]:
t= torch.rand(3,3)
print(t)
t + y

tensor([[0.1547, 0.7626, 0.4469],
        [0.2692, 0.4267, 0.8163],
        [0.5971, 0.2007, 0.9489]])


tensor([[1.1547, 2.7626, 3.4469],
        [2.2692, 3.4267, 4.8163],
        [0.5971, 0.2007, 0.9489]])