<a href="https://colab.research.google.com/github/ascalmon/Colab-test/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [6]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [4]:
y = torch.tensor([
    [1,2,3],
    [2,3,4],
    [0,0,0]
], dtype=torch.float)
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [ ]:
torch.ones(1,2, dtype=torch.int)

In [ ]:
torch.zeros(5,3, 2, dtype=torch.float)

In [5]:
z = torch.rand(3, 4, 2, dtype=torch.float)
z

tensor([[[0.5991, 0.2754],
         [0.6241, 0.3371],
         [0.2324, 0.2340],
         [0.8694, 0.9218]],

        [[0.2289, 0.8394],
         [0.7797, 0.8148],
         [0.5120, 0.3383],
         [0.7391, 0.8664]],

        [[0.8080, 0.5865],
         [0.4940, 0.9067],
         [0.3779, 0.5964],
         [0.6811, 0.5144]]])

In [19]:
print(y)
y[0]


tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


tensor([1., 2., 3.])

In [20]:
y[:, 1]

tensor([2., 3., 0.])

In [24]:
z[2, : ,0]

tensor([0.7207, 0.0082, 0.5020, 0.4439])

In [25]:
y[:,0]

tensor([1., 2., 0.])

In [28]:
print(y)
y.size()

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


torch.Size([3, 3])

In [29]:
print(y)
y.size()[0]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


3

In [33]:
t= torch.rand(3,3)
print(t)
t + y

tensor([[0.1547, 0.7626, 0.4469],
        [0.2692, 0.4267, 0.8163],
        [0.5971, 0.2007, 0.9489]])


tensor([[1.1547, 2.7626, 3.4469],
        [2.2692, 3.4267, 4.8163],
        [0.5971, 0.2007, 0.9489]])

In [6]:
y.reshape(1,9)

tensor([[1., 2., 3., 2., 3., 4., 0., 0., 0.]])

In [7]:
y.reshape(-1,)

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [10]:
torch.squeeze(y.reshape(1, 9))

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [11]:
y.sum()

tensor(15.)

In [12]:
y.sum(0)

tensor([3., 5., 7.])

In [13]:
torch.max(y)

tensor(4.)

In [17]:
values, indices = torch.max(y, 0)
print(values)
print(indices)

tensor([2., 3., 4.])
tensor([1, 1, 1])


In [18]:
y[0, 0].item() == 1

True

In [19]:
y.numpy()

array([[1., 2., 3.],
       [2., 3., 4.],
       [0., 0., 0.]], dtype=float32)

In [23]:
import numpy as np

a = np.array([[1,2], [3,4]])
b = torch.from_numpy(a)
b

tensor([[1, 2],
        [3, 4]])

In [26]:
a[0,0] = 5
a

array([[5, 2],
       [3, 4]])

In [27]:
b

tensor([[5, 2],
        [3, 4]])